newproject/myapp/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
   path('add/', views.student, name='myapp-views-student'),
   path('list/', views.list, name='myapp-views-list'),
   path('student/<int:id>/', views.detail, name='myapp-views-detail'),
   path('student-delete/<int:id>/', views.delete, name='myapp-views-delete'),
   path('student-update/<int:id>/', views.update, name='myapp-views-update')




]

newproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('myapp.urls'))
]

newproject/myapp/models.py
from django.db import models

# Create your models here.
# creating a student model

class students(models.Model):
    name=models.CharField(max_length=30)
    age=models.IntegerField(null=True)
    id=models.AutoField(primary_key=True)
    grade=models.CharField(max_length=1)

    class Meta:
        verbose_name_plural = "students"


    def __str__(self):
        return self.name

newproject/myapp/forms.py
# from django import forms


# class ContactForm(forms.Form):
#     subject = forms.CharField(max_length=100)
#     message = forms.CharField(widget=forms.Textarea)
#     sender = forms.EmailField()
#     # cc_myself = forms.BooleanField(required=False)

newproject/myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import students
from .forms import *
# from templates import updateForm


# # Create your views here.

def list(request):
    student_list=students.objects.all()
    context={'student_list':student_list}
    return render(request,'myapp/index.html',context=context)

def student(request):
    if request.method=='POST':
        student = students()
        student.name = request.POST.get("name")
        student.age = request.POST.get("age")
        student.grade = request.POST.get("grade")

        if student.grade is not None:
            student.save()
            return redirect('/students/list/')
        else:
            # Handle the case where 'grade' is empty
            return HttpResponse("Grade cannot be empty")

    else:
        return render(request,'myapp/add_student.html')
    

def detail(request,id):
    student_single=students.objects.get(id=id)
    context={'student_single':student_single}
    return render(request,'myapp/detail.html',context=context)

def delete(request, id):
    student = students.objects.get(id=id)
    student.delete()
    context={'message': 'Student has been deleted'}
    return redirect('/students/list/')


def update(request,id):
    if request.method == 'POST':
        instance= students.objects.get(id=id)
        context={'instance':instance}
        return render(request, 'myapp/updateForm.html', context=context)
    else:
        return render(request, 'myapp/updateForm.html')

newproject/myapp/templates/myapp/add_student.html
<h1>Add Student</h1>


<form method="POST" action="{% url 'myapp:myapp-views-student' %}" >
    {% csrf_token %}
    Name:<br>
    <input name="name">
    <br><br>
    Age:<br>
    <input name="age">
    <br><br>
    grade:<br>
    <input name="grade">
    <br><br>

    <br><br>
    <input type="submit" value="Submit">
</form>

newproject/myapp/templates/myapp/detail.html
<head>
    <title>Student Information</title>
  </head>
  
  <body>
    

    <p> {{student_single.name}}</p>
    

    {% comment %}  
    <a href=    "{% url 'myapp:student_view' %}" >Add Student</a>
      
    {% endcomment %}
  </body>
  
</html>

newproject/myapp/templates/myapp/index.html
<head>
    <title>Student Information</title>
  </head>
  
  <body>
    
    {% if student_list %}
    <ul>
        {% for student in student_list %}
        <li> <b> {{student.name}} </b> | {{student.age}} </b> | {{student.grade}} </li> <a href="{% url 'myapp:myapp-views-detail' student.id %}"> Student Detail</a>
        <a href="{% url 'myapp:myapp-views-delete' student.id %}"> Student Delete</a>
        <a href="{%url 'myapp:myapp-views-update' student.id %}">Update Student</a>
        {% endfor %}
    </ul>
    {% else %}
    <p>No student information available in the database. </p>
    {% endif %}

    <a href="{% url 'myapp:myapp-views-student' %}" >Add Student</a>
    
  </body>
  
</html>

newproject/myapp/templates/myapp/updateForm.html
<h1>Update Student</h1>


<form method="POST" >
    {% csrf_token %}
    Name:<br>
    <input value={{instance.name}}>
    <br><br>
    Age:<br>
    <input value={{instance.age}}>
    <br><br>
    grade:<br>
    <input value={{instance.grade}}>
    <br><br>

    <br><br>
    <input type="submit" value="Update">
</form>